name = "sorteo-quimpac"
main = ".open-next/worker.js"
compatibility_date = "2025-10-08"
compatibility_flags = [
  "nodejs_compat",
  "global_fetch_strictly_public"
]

[env.production]
name = "sorteo-quimpac-prod"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true

upload_source_maps = true
